---
title: "p8105_hw3_hy2669"
author: "haoyang,yi"
date: "2020/10/9"
output: github_document
---

```{r setup, include=FALSE}
library(p8105.datasets)
library(tidyverse)
library(patchwork)
library(rnoaa)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp=0.6,
  out.width = '90%'
)
theme_set(theme_minimal())
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1
```{r}
data("instacart")
```

The dataset contains `r nrow(instacart)` rows and `r ncol(instacart)` columns. Observations are level of items in orders by user, information of items.
```{r}
instacart %>% 
  count(aisle) %>% 
  arrange(desc(n))
```

```{r}
instacart %>% 
  count(aisle) %>% 
  filter(n>10000) %>%
  mutate(aisle = factor(aisle),
         aisle = fct_reorder(aisle,n)) %>% 
  ggplot(aes(x = aisle,y = n)) +
  geom_point()+
  theme(axis.text.x = element_text(angle=90,vjust=0.5,hjust=1))
```
